server:
  port: 9004

spring:
  application:
    name: consumer_nacos_openFeign

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 4e0c659b-264b-4b61-b049-1037390ae3d5
        username: nacos
        password: nacos
        group: dev
    openfeign:
      client:
        config:
          default: # default 表示全局设置
            connect-timeout: 2000   # 连接超时时间 (毫秒)
            read-timeout: 5000      # 读取超时时间 (毫秒)