server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_cloud?useSSL=false&serverTimezone=UTC
    username: root
    password: aA1472580@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: provider-service-rest
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl